version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: Node-Dyanmic-Dns-For-Dreamhost
    restart: unless-stopped
    environment:
      - DH_API_KEY=$DH_API_KEY
      - HOSTNAMES=$HOSTNAMES
    ports:
      - 6060:6060
    healthcheck:
      test: curl -f http://localhost:6060/health || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 5s